### ISSUE TITLE
New project build error

### ISSUE THREAD

**Issue by corelevel** [esp-rs/esp-idf-template#181] opened 2024-01-06 16:13 UTC
Got a build error on new project:
`cannot find value `SOMAXCONN` in crate `libc``

## To Reproduce
Install Rust, install [prerequisites](https://github.com/esp-rs/esp-idf-template#prerequisites)
Run
`PS C:\Dev\esp32> cargo generate https://github.com/esp-rs/esp-idf-template cargo
 Favorite `https://github.com/esp-rs/esp-idf-template` not found in config, using it as a git repository: https://github.com/esp-rs/esp-idf-template
 Project Name: my-new-p
 Destination: C:\Dev\esp32\my-new-p ...
 project-name: my-new-p ...
 Generating template ...
✔  Which MCU to target? · esp32c6
✔  Configure advanced template options? · false
 Moving generated files into: `C:\Dev\esp32\my-new-p`...
 Initializing a fresh Git repository
 Done! New project created C:\Dev\esp32\my-new-p
PS C:\Dev\esp32> cd .\my-new-p\
PS C:\Dev\esp32\my-new-p> cargo build
    Updating crates.io index
   Compiling compiler_builtins v0.1.103
   Compiling core v0.0.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core)
   Compiling proc-macro2 v1.0.76
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.150
   Compiling memchr v2.5.0
   Compiling std v0.0.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std)
   Compiling serde v1.0.195
   Compiling windows_x86_64_msvc v0.48.5
   Compiling windows_x86_64_msvc v0.52.0
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.1
   Compiling windows-targets v0.48.5
   Compiling winapi v0.3.9
   Compiling windows-sys v0.48.0
   Compiling windows-targets v0.52.0
   Compiling windows-sys v0.52.0
   Compiling regex-syntax v0.8.2
   Compiling crossbeam-utils v0.8.18
   Compiling quote v1.0.35
   Compiling aho-corasick v1.1.2
   Compiling syn v2.0.48
   Compiling semver v1.0.21
   Compiling windows_x86_64_msvc v0.42.2
   Compiling syn v1.0.109
   Compiling regex-automata v0.4.3
   Compiling glob v0.3.1
   Compiling winapi-util v0.1.6
   Compiling log v0.4.20
   Compiling clang-sys v1.7.0
   Compiling libc v0.2.151
   Compiling rustix v0.38.28
   Compiling stable_deref_trait v1.2.0
   Compiling rustversion v1.0.14
   Compiling as-slice v0.2.1
   Compiling same-file v1.0.6
   Compiling crossbeam-epoch v0.9.17
   Compiling errno v0.3.8
   Compiling bstr v1.9.0
   Compiling once_cell v1.19.0
   Compiling thiserror v1.0.56
   Compiling bitflags v2.4.1
   Compiling serde_json v1.0.111
   Compiling minimal-lexical v0.2.1
   Compiling globset v0.4.14
   Compiling nom v7.1.3
   Compiling crossbeam-deque v0.8.4
   Compiling walkdir v2.4.0
   Compiling windows-targets v0.42.2
   Compiling aligned v0.4.1
   Compiling home v0.5.9
   Compiling libloading v0.8.1
   Compiling cvt v0.1.2
   Compiling anyhow v1.0.79
   Compiling ryu v1.0.16
   Compiling heck v0.4.1
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling either v1.9.0
   Compiling itoa v1.0.10
   Compiling bindgen v0.63.0
   Compiling which v4.4.2
   Compiling cexpr v0.6.0
   Compiling fs_at v0.1.10
   Compiling windows-sys v0.45.0
   Compiling ignore v0.4.21
   Compiling regex v1.10.2
   Compiling normpath v1.1.1
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling shlex v1.2.0
   Compiling fastrand v2.0.1
   Compiling cc v1.0.83
   Compiling rustc-std-workspace-core v1.99.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\rustc-std-workspace-core)
   Compiling alloc v0.0.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc)
   Compiling unwind v0.0.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\unwind)
   Compiling adler v1.0.2
   Compiling rustc-demangle v0.1.23
   Compiling serde_derive v1.0.195
   Compiling thiserror-impl v1.0.56
   Compiling rustc-std-workspace-alloc v1.99.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\rustc-std-workspace-alloc)
   Compiling gimli v0.28.0
   Compiling hashbrown v0.14.3
   Compiling std_detect v0.1.5 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\stdarch\crates\std_detect)
   Compiling object v0.32.1
   Compiling miniz_oxide v0.7.1
   Compiling panic_abort v0.0.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\panic_abort)
   Compiling panic_unwind v0.0.0 (C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\panic_unwind)
   Compiling strum_macros v0.24.3
   Compiling addr2line v0.21.0
   Compiling peeking_take_while v0.1.2
   Compiling cmake v0.1.50
   Compiling remove_dir_all v0.8.2
   Compiling tempfile v3.9.0
   Compiling globwalk v0.8.1
   Compiling filetime v0.2.23
   Compiling camino v1.1.6
   Compiling ident_case v1.0.1
   Compiling fnv v1.0.7
   Compiling autocfg v1.1.0
   Compiling darling_core v0.20.3
   Compiling unicode-xid v0.2.4
error[E0425]: cannot find value `SOMAXCONN` in crate `libc`
  --> C:\Users\corel\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\os\unix\net\listener.rs:87:48
   |
87 |             const backlog: libc::c_int = libc::SOMAXCONN;
   |                                                ^^^^^^^^^ not found in `libc`

   Compiling num-traits v0.2.17
   Compiling embassy-time v0.1.5
   Compiling const_format_proc_macros v0.2.32
   Compiling strum v0.24.1
   Compiling version_check v0.9.4
   Compiling embassy-sync v0.3.0
For more information about this error, try `rustc --explain E0425`.
error: could not compile `std` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...`

## Expected behavior
The project builds successfully

## Environment
- OS: Windows 11
- How did you install the environment: espup v0.10.0

**Comment by ivmarkov** [comment] 2024-01-06 18:02
Duplicate of https://github.com/rust-lang/rust/pull/119632

Don't use latest nightly for a while.

**Closed by ivmarkov** 2024-01-06 18:02 UTC
Labels: bug
